import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen overflow-scroll snap-y snap-mandatory scrollbar-hide">
        <div className="flex items-center justify-center w-screen h-screen bg-amber-200 snap-start text-8xl">
          1
        </div>
        <div className="flex items-center justify-center w-screen h-screen bg-teal-200 snap-start text-8xl">
          2
        </div>
        <div className="flex items-center justify-center w-screen h-screen bg-cyan-200 snap-start text-8xl">
          3
        </div>
        <div className="flex items-center justify-center w-screen h-screen bg-fuchsia-200 snap-start text-8xl">
          4
        </div>
      </div>
    </>
  )
}

export default Home
