import type { NextPage } from 'next'
import Head from 'next/head'
import React, { Component } from 'react'

class CommonArticle extends Component<{ children: React.ReactNode }> {
  render() {
    return (
      <article className="flex items-center justify-center w-screen h-screen bg-amber-200 snap-start text-8xl">
        {this.props.children}
      </article>
    )
  }
}
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="h-screen overflow-scroll snap-y snap-mandatory scrollbar-hide">
        <CommonArticle>1</CommonArticle>
        <CommonArticle>2</CommonArticle>
        <CommonArticle>3</CommonArticle>
        <CommonArticle>4</CommonArticle>
      </section>
    </>
  )
}

export default Home
