import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import Snap from '../components/snap'
import Typing from '../components/typing'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Snap>
        <Snap.Article>
          <Typing
            letters={['어서 운동을 인증해!', '너의 식단을 보여줘!']}
            loop
          />
        </Snap.Article>
        <Snap.Article>2</Snap.Article>
        <Snap.Article>3</Snap.Article>
        <Snap.Article>4</Snap.Article>
      </Snap>
    </>
  )
}

export default Home
